set nocompatible  " be iMproved, required
filetype off  " required
set exrc


set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" ==== plugin manager
Plugin 'VundleVim/Vundle.vim'

" ==== helpers
" Plugin 'vim-scripts/L9'

" ==== File tree
Plugin 'scrooloose/nerdtree'

" ==== Completion
"Plugin 'Valloric/YouCompleteMe'

" ==== Git
Plugin 'airblade/vim-gitgutter'
Plugin 'tpope/vim-fugitive'


" ==== syntax helpers
" Plugin 'scrooloose/syntastic'
" Plugin 'tpope/vim-surround'
Plugin 'cakebaker/scss-syntax.vim'
Plugin 'othree/yajs.vim'
Plugin 'mxw/vim-jsx'

" Plugin 'mitsuhiko/vim-jinja'
" Plugin 'octol/vim-cpp-enhanced-highlight'
" Plugin 'ap/vim-css-color'
" Plugin 'Vimjas/vim-python-pep8-indent'

" ==== moving / searching
" Plugin 'easymotion/vim-easymotion'
" Plugin 'kien/ctrlp.vim'

" ==== snippets
" -- Plugin 'SirVer/ultisnips' " It's for python, I don't need it

" Status bar on bottom
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'


" ==== PLUGIN THEMES
" Plugin 'morhetz/gruvbox'
" Plugin 'ryanoasis/vim-devicons'


" ==== Custom Tmp


call vundle#end()
filetype plugin indent on


" ==== Colors and other basic settings
colorscheme gruvbox
set guifont=Menlo\ 10
set fillchars+=vert:\$
syntax enable
set background=dark
" set ruler
" set hidden
" set number
set laststatus=2
set smartindent
set st=4 sw=4 et
set shiftwidth=2
set tabstop=2
set expandtab
autocmd FileType js,jsx,css,scss,html,json  set shiftwidth=2 | set expandtab
" let &colorcolumn = '80'
:set guioptions-=m  "remove menu bar
:set guioptions-=T  "remove toolbar
:set guioptions-=r  "remove right-hand scroll bar
:set guioptions-=L  "remove left-hand scroll bar
:set lines=999 columns=999


" ==== NERDTREE
let NERDTreeIgnore = ['__pycache__', '\.pyc$', '\.o$', '\.so$', '\.a$', '\.swp', '*\.swp', '\.swo', '\.swn', '\.swh', '\.swm', '\.swl', '\.swk', '\.sw*$', '[a-zA-Z]*egg[a-zA-Z]*', '.DS_Store']
let NERDTreeShowHidden = 1
" let g:NERDTreeWinPos = 'left'
let g:NERDTreeDirArrows = 0
map <C-t> :NERDTreeToggle<CR>
" map <Space-p-t> :NERDTreeToggle<CR>


" ==== Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
" set statusline+=%#warningmsg#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*
let g:syntastic_javascript_checkers = ['eslint']
let g:syntastic_javascript_mri_args = "--config=$HOME/.jshintrc"
" let g:syntastic_python_checkers = [ 'pylint', 'flake8', 'pep8', 'pyflakes', 'python']
" let g:syntastic_yaml_checkers = ['jsyaml']
let g:syntastic_html_tidy_exec = 'tidy5'


" === flake8 for pyhton
" let g:flake8_show_in_file=1


" ==== snippets
" let g:UltiSnipsExpandTrigger="<A-ENTER>"
" let g:UltiSnipsJumpForwardTrigger="<A-ENTER>"
" let g:UltiSnipsJumpBackwardTrigger="<A-BACKSPACE>"
" If you want :UltiSnipsEdit to split your window.
" let g:UltiSnipsEditSplit = 'vertical'


" ==== Easymotion
" let g:EasyMotion_do_mapping = 0
" let g:EasyMotion_smartcase = 1
" nmap f <Plug>(easymotion-s)


" ==== moving around
" nmap <silent> <A-Up> :wincmd k<CR>
" nmap <silent> <A-Down> :wincmd j<CR>
" nmap <silent> <A-Left> :wincmd h<CR>
" nmap <silent> <A-Right> :wincmd l<CR>


" ==== disable mouse
set mouse=c


" ==== disable swap file warning
set shortmess+=A


" ==== custom commands
" command JsonPretty execute ":%!python -m json.tool"
" set secure


" custom
set hlsearch
" control the behave of backspace
" set backspace=indent,eol,start
imap fd <Esc>
let g:airline_theme = 'simple'
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ' '
" let g:airline#extensions#tabline#left_alt_sep = ' '
let g:airline#extensions#tabline#formatter = 'unique_tail_improved'


" key map
nmap <C-h> <C-W>h
nmap <C-j> <C-W>j
nmap <C-k> <C-W>k
nmap <C-l> <C-W>l
" nmap <C-s> :w<CR>
nmap <C-s> :update<CR>
vmap <C-s> <C-C>:update<CR>
imap <C-s> <C-O>:update<CR>
